
columns_simple = [
                  {"id": '220161947', 'column': 'respondente_nome'}, 
                  {"id": '224174967', 'column': 'respondente_email'}, 
                  {"id": '224175004', 'column': 'respondente_telefone'}, 
                  {"id": '220161943', 'column': 'normas'}, 
                  {"id": '220161949', 'column': 'volume_anual'}, 
                  {"id": '220161918', 'column': 'qtd_areas_envolvidas'}, 
                  {"id": '220161941', 'column': 'qtd_dias_espera'},
                  {"id": '220161942', 'column': 'qtd_interacoes'},
                  {"id": '220161957', 'column': 'qtd_pessoas_implantacao'}, 
                  {"id": '220161958', 'column': 'tempo_pessoas_implantacao'}] 

columns_categoric = [
                    {"id": '220161945', 'column': 'tipo_usuario'}, 
                    {"id": '220161961', 'column': 'forma_prestacao'}, 
                    {"id": '220161915', 'column': 'sn_medicao_tempo_entrega'}, 
                    {"id": '220161916', 'column': 'canais_oferecidos'}, 
                    {"id": '220161948', 'column': 'sn_processo_aval_qualidade'},
                    {"id": '220161917', 'column': 'sn_usa_reclamacoes'},
                    {"id": '220161919', 'column': 'sn_capacitacao_colaboradores'}, 
                    {"id": '220161920', 'column': 'sn_incentivo_colaboradores'}, 
                    {"id": '220161922', 'column': 'custo_instituicao'}, 
                    {"id": '220161923', 'column': 'sn_custo_rh_total'}, 
                    {"id": '220161927', 'column': 'sn_custo_usuario_total'}, 
                    {"id": '220161938', 'column': 'custo_usuario'}, 
                    {"id": '220161951', 'column': 'renda_mensal_usuario'}, 
                    {"id": '220161952', 'column': 'representante_pj'}, 
                    {"id": '220161963', 'column': 'sn_cadastro_solicitacoes'}, 
                    {"id": '220161928', 'column': 'sn_servico_plano_estrategico'}, 
                    {"id": '220161929', 'column': 'sn_modelo_gestao_qualidade'}, 
                    {"id": '220161931', 'column': 'sn_avaliacao_qualidade_regular'}, 
                    {"id": '220161932', 'column': 'sn_pessoas_exclusiv_qualidade'},
                    {"id": '220161933', 'column': 'sn_ferramenta_aval_satisfacao'},
                    {"id": '220161934', 'column': 'sn_usuarios_envolv_melhoria'}, 
                    {"id": '220161936', 'column': 'sn_colaboracao_instituicoes'}] 

columns_multiple = [
            {"id": '241010906', 'sub_id': '1644586885', 'column': 'rat_buscainf_presencial_antes'}, 
            {"id": '241010906', 'sub_id': '1644586886', 'column': 'rat_buscainf_digital_antes'}, 
            {"id": '241010906', 'sub_id': '1644586889', 'column': 'rat_buscainf_telefone_antes'}, 
            {"id": '220161921', 'sub_id': '1511913176', 'column': 'cb_transf_conhecimento'}, 
            {"id": '220161921', 'sub_id': '1511913177', 'column': 'cb_politica_capacitacao'}, 
            {"id": '220161921', 'sub_id': '1511913178', 'column': 'cb_qtd_colab_adequado'}, 
            {"id": '220161921', 'sub_id': '1511913179', 'column': 'cb_treinamento_inicio'}, 
            {"id": '220161921', 'sub_id': '1511913180', 'column': 'cb_selecao_colaboradores'}, 
            {"id": '220161950', 'sub_id': '1511913436', 'column': 'doc_necessarios_1'}, 
            {"id": '220161950', 'sub_id': '1511913473', 'column': 'doc_necessarios_2'}, 
            {"id": '220161950', 'sub_id': '1511913474', 'column': 'doc_necessarios_3'}, 
            {"id": '220161950', 'sub_id': '1511913475', 'column': 'doc_necessarios_4'}, 
            {"id": '220161950', 'sub_id': '1511913476', 'column': 'doc_necessarios_5'}, 
            {"id": '220161924', 'sub_id': '1511913187', 'column': 'inform_docs_necessarios'}, 
            {"id": '220161924', 'sub_id': '1511913362', 'column': 'inform_etapas_necessarias'}, 
            {"id": '220161924', 'sub_id': '1511913188', 'column': 'realizar_agendamento'}, 
            {"id": '220161924', 'sub_id': '1511913189', 'column': 'consultar_agendamento'}, 
            {"id": '220161924', 'sub_id': '1511913190', 'column': 'solicitar_servico'}, 
            {"id": '220161924', 'sub_id': '1511913191', 'column': 'acompanhar_servico'}, 
            {"id": '220161924', 'sub_id': '1511913363', 'column': 'registrar_reclamacao'}, 
            {"id": '220161924', 'sub_id': '1511913192', 'column': 'resposta_reclamacao'}, 
            {"id": '220161924', 'sub_id': '1511913364', 'column': 'assinar_documento'}, 
            {"id": '220161924', 'sub_id': '1511913365', 'column': 'fazer_pagamento'}, 
            {"id": '220161925', 'sub_id': '1511913193', 'column': 'disponibilidade_sistemas'},
            {"id": '220161925', 'sub_id': '1511913194', 'column': 'facilita_gestao'},
            {"id": '220161925', 'sub_id': '1511913195', 'column': 'informacoes_confiaveis'},
            {"id": '220161925', 'sub_id': '1511913196', 'column': 'suporte_completo_servico'},
            {"id": '220161925', 'sub_id': '1511913397', 'column': 'dados_formato_aberto'},
            {"id": '220161925', 'sub_id': '1511913398', 'column': 'acessibilidade_sistema'}, 
            {"id": '220161926', 'sub_id': '1511913201', 'column': 'reduzir_qtd_documentos'}, 
            {"id": '220161926', 'sub_id': '1511913202', 'column': 'divulgacao_desempenho'},
            {"id": '220161930', 'sub_id': '1511913213', 'column': 'ad_missao_servicos'},
            {"id": '220161930', 'sub_id': '1511913214', 'column': 'ad_monitora_qualidade'},
            {"id": '220161930', 'sub_id': '1511913215', 'column': 'ad_divulga_servicos'},
            {"id": '220161930', 'sub_id': '1511913216', 'column': 'ad_melhoria_processos'},
            {"id": '220161935', 'sub_id': '1511913229', 'column': 'estrategia_divulgacao_efetiva'}, 
            {"id": '220161937', 'sub_id': '1511913236', 'column': 'proatividade_divulgacao_informacoes'},
            {"id": '220161962', 'sub_id': '1511913745', 'column': 'sistema_etapas_solicitacao'}, 
            {"id": '220161962', 'sub_id': '1511913746', 'column': 'sistema_etapas_analise'}, 
            {"id": '220161962', 'sub_id': '1511913747', 'column': 'sistema_etapas_entrega'}, 
            ]

columns_matrix = [
    {"id": '220161959', 'row_id': '1511913706', 'col_id': '1581604351', 'column': 'rat_solicitacao_antes_presencial'}, 
    {"id": '220161959', 'row_id': '1511913707', 'col_id': '1581604351', 'column': 'rat_solicitacao_antes_digital'}, 
    {"id": '220161959', 'row_id': '1581604328', 'col_id': '1581604351', 'column': 'rat_solicitacao_antes_postal'}, 
    {"id": '220161959', 'row_id': '1581604329', 'col_id': '1581604351', 'column': 'rat_solicitacao_antes_telefone'}, 
    {"id": '220161959', 'row_id': '1511913706', 'col_id': '1581604378', 'column': 'rat_entrega_antes_presencial'},
    {"id": '220161959', 'row_id': '1511913707', 'col_id': '1581604378', 'column': 'rat_entrega_antes_digital'},
    {"id": '220161959', 'row_id': '1581604328', 'col_id': '1581604378', 'column': 'rat_entrega_antes_postal'},
    {"id": '220161959', 'row_id': '1581604329', 'col_id': '1581604378', 'column': 'rat_entrega_antes_telefone'},
    {"id": '241002894', 'row_id': '1644533037', 'col_id': '1644533068', 'column': 'rat_entrega_depois_presencial'}, 
    {"id": '220161953', 'row_id': '1511913710', 'col_id': '1581646209', 'column': 'rat_entrega_depois_digital'}, 
    # {"id": '241002894', 'row_id': '1644533038', 'col_id': '1644533068', 'column': 'rat_entrega_depois_digital'}, 
    {"id": '241002894', 'row_id': '1644533040', 'col_id': '1644533068', 'column': 'rat_entrega_depois_postal'}, 
    {"id": '241002894', 'row_id': '1644533041', 'col_id': '1644533068', 'column': 'rat_entrega_depois_telefone'}, 
    {"id": '241002894', 'row_id': '1644533037', 'col_id': '1644533045', 'column': 'rat_solicitacao_depois_presencial'},
    # {"id": '241002894', 'row_id': '1644533038', 'col_id': '1644533045', 'column': 'rat_solicitacao_depois_digital'}, 
    {"id": '220161953', 'row_id': '1511913709', 'col_id': '1581646209', 'column': 'rat_solicitacao_depois_digital'},
    {"id": '241002894', 'row_id': '1644533040', 'col_id': '1644533045', 'column': 'rat_solicitacao_depois_postal'}, 
    {"id": '241002894', 'row_id': '1644533041', 'col_id': '1644533045', 'column': 'rat_solicitacao_depois_telefone'},
    {"id": '220161953', 'row_id': '1511913458', 'col_id': '1581646209', 'column': 'rat_buscainf_presencial_depois'},  
    {"id": '220161953', 'row_id': '1511913457', 'col_id': '1581646209', 'column': 'rat_buscainf_digital_depois'},  
    {"id": '220161953', 'row_id': '1511913458', 'col_id': '1581646209', 'column': 'rat_buscainf_telefone_depois'},  
    {"id": '220161953', 'row_id': '1511913459', 'col_id': '1581646209', 'column': 'red_docs_solicitados'},  
    {'id': '220161954', "row_id": '1581480806', 'col_id': '1581480808', 'column': 'qtd_servidores_antes'}, 
    {'id': '220161954', "row_id": '1581480806', 'col_id': '1582860212', 'column': 'percentual_servidores_antes'}, 
    {'id': '220161954', "row_id": '1581480807', 'col_id': '1581480808', 'column': 'qtd_terceirizados_antes'}, 
    {'id': '220161954', "row_id": '1581480807', 'col_id': '1582860212', 'column': 'percentual_terceirizados_antes'}, 
    {'id': '230931417', "row_id": '1581517691', 'col_id': '1581531845', 'column': 'qtd_servidores_depois'}, 
    {'id': '230931417', "row_id": '1581517687', 'col_id': '1581531845', 'column': 'percentual_servidores_depois'}, 

    {'id': None, "row_id": '1664189140', 'col_id': '1664189141', 'column': 'qtd_terceirizados_depois', 'question': 'Após a transformação do serviço, estime quantos colaboradores se dedicariam a ofertar o serviço e qual seria o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.'},
    {'id': None, "row_id": '1664189140', 'col_id': '1664189231', 'column': 'percentual_terceirizados_depois', 'question': 'Após a transformação do serviço, estime quantos colaboradores se dedicariam a ofertar o serviço e qual seria o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.'}, ##NONE

    ]


columns_other = [
    {"id": '1538043547', 'column': 'nome_servico_outro'}, 
    {"id": '1511913391', 'column': 'canais_oferecidos_outro'}, 
    {"id": '1511913708', 'column': 'rat_utilizacao_antes_outro'},
    {"id": '1644533039', 'column': 'rat_utilizacao_depois_outro'},
    {"id": '1511913454', 'column': 'representante_pj_outro'}, 
    {"id": '1511913439', 'column': 'doc_necessarios_outro'}, 
    {"id": '1582971570', 'column': 'acoes_internet_outro'}, 
    {"id": '1644654377', 'column': 'adequabilidade_sistemas'}, 
    {"id": '1581701712', 'column': 'melhorias_servico_outro'}, 
    {"id": '1511913443', 'column': 'colaboracao_instituicoes_outro'}, 
                 ]
#
columns_nomes = [
    {"id": '220161939', 'column': 'qtd_servicos', "rows":['1511913271','1511913274','1511913275','1511913630','1511913463'], 'col_id':'1511959873'},
    {"id": '220161939', 'column': 'nome_servico', "rows":['1511913271','1511913274','1511913275','1511913630','1511913463'], 'col_id':'1524947137'},
    {"id": None, 'column': 'organizacao'}

]
# columns_simple = [
#                     {'question': 'Quantos serviços você coordena?', 'column': 'qtd_servicos', 'id': '241294964'},
#                     {'question': 'Qual é o seu nome?', 'column': 'respondente_nome', 'id': '241286639'},
#                     {'question': 'Qual é o seu email?(OBS: formato xxxxxx@xxxxxx.gov.br)', 'column': 'respondente_email', 'id': '241286654'},
#                     {'question': 'Qual é o seu telefone?(Obs: todos os números juntos no formato 9999999999, incluindo DDD)', 'column': 'respondente_telefone', 'id': '241286655'},
#                     {'question': 'Quais são as principais normas que regulam o serviço?(ex: leis, decretos, instruções normativas, portarias, etc)', 'column': 'normas', 'id': '241286637'},
#                     {'question': 'Qual é a estimativa do volume anual de solicitações do serviço?(Obs: é possível digitar o número desejado no campo à direita, sem utilizar a barra de rolagem)', 'column': 'volume_anual', 'id': '241286641'},
#                     {'question': 'Quantas áreas da instituição estão envolvidas na prestação do serviço?(área: setor que representa menor nível hierárquico no organograma da instituição)', 'column': 'qtd_areas_envolvidas', 'id': '241286613'},
#                     {'question': 'Quantos dias o usuário espera até a efetiva entrega do serviço?', 'column': 'qtd_dias_espera', 'id': '241286635'},
#                     {'question': 'De forma estimada, quantas vezes o usuário interage com a instituição até a entrega do serviço?(interação: cada vez que um\xa0usuário se relaciona com a\xa0instituição durante a prestação do serviço)', 'column': 'qtd_interacoes', 'id': '241286636'},
#                     {'question': 'Quantos colaboradores se dedicariam ao projeto de desenvolvimento e implantação da política de transformação do serviço?', 'column': 'qtd_pessoas_implantacao', 'id': '241286647'},
#                     {'question': 'Qual seria o tempo estimado de dedicação semanal dos colaboradores em horas?', 'column': 'tempo_pessoas_implantacao', 'id': '241286648'}
#                 ]
#
# columns_categoric = [
#                         {'question': 'A qual instituição você pertence?', 'column': 'organizacao', 'id': '241301514'},
#                         {'question': 'Informe o nome do serviço que será avaliado nessa pesquisa.(OBS: é possível buscar por serviço clicando no menu suspenso e digitando a primeira letra do nome do serviço desejado)', 'column': 'nome_servico', 'id': '241286634'},
#                         {'question': 'O serviço\xa0é oferecido a pessoas físicas, jurídicas ou ambas?', 'column': 'tipo_usuario', 'id': '241286638'},
#                         {'question': 'Qual é a forma de prestação do serviço?', 'column': 'forma_prestacao', 'id': '241286650'},
#                         {'question': 'Há medições do tempo de espera do usuário até a entrega do serviço?(entrega: ato administrativo final que implica no recebimento do serviço pelo usuário)', 'column': 'sn_medicao_tempo_entrega', 'id': '241286610'},
#                         {'question': 'Quais canais de atendimento são oferecidos para o relacionamento com os usuários do serviço?', 'column': 'canais_oferecidos', 'id': '241286611'},
#                         {'question': 'Há processo de avaliação da qualidade do atendimento oferecido ao usuário do serviço?', 'column': 'sn_processo_aval_qualidade', 'id': '241286640'},
#                         {'question': 'A sua instituição faz uso dos dados de reclamações e sugestões para a melhoria do serviço?', 'column': 'sn_usa_reclamacoes', 'id': '241286612'},
#                         {'question': 'Há ações de capacitação da instituição voltadas diretamente para o serviço analisado (considere apenas os treinamentos ligados ao serviço analisado, e não da instituição como um todo)?', 'column': 'sn_capacitacao_colaboradores', 'id': '241286614'},
#                         {'question': 'São oferecidos incentivos aos colaboradores pelo seu desempenho associado à melhoria da qualidade dos serviços?', 'column': 'sn_incentivo_colaboradores', 'id': '241286615'},
#                         {'question': 'Qual é a estimativa de custo anual total do serviço para a instituição? (Itens: recursos humanos/quadro de colaboradores, locação ou manutenção da infraestrutura e Tecnologia da Informação)', 'column': 'custo_instituicao', 'id': '241286617'},
#                         {'question': 'Há indicador do custo dos Recursos Humanos em relação ao gasto total com o serviço?', 'column': 'sn_custo_rh_total', 'id': '241286618'},
#                         {'question': 'Há mensuração do custo total para o usuário? (Custo total para o usuário: inclui taxas, gastos com deslocamento, alimentação, tempo de espera, etc)', 'column': 'sn_custo_usuario_total', 'id': '241286622'},
#                         {'question': 'Caso "Sim", quais são os custos estimados para o usuário (taxas, tarifas, custos de deslocamento, outros)?', 'column': 'custo_usuario', 'id': '241286633'},
#                         {'question': 'De forma estimada, qual seria a renda média mensal do usuário típico do serviço?', 'column': 'renda_mensal_usuario', 'id': '241286643'},
#                         {'question': 'Se o solicitante é pessoa jurídica, qual(ais) o(s) perfil(is) profissional(is) mais se aproxima(m) do(s) possível(eis) usuário(s) típico(s) que realizam as atividades exigidas pelo serviço?', 'column': 'representante_pj', 'id': '241286644'},
#                         {'question': 'As solicitações de serviço recebidas geram algum cadastro eletrônico para a instituição?', 'column': 'sn_cadastro_solicitacoes', 'id': '241286652'},
#                         {'question': 'O serviço está contemplado\xa0no plano estratégico da instituição?', 'column': 'sn_servico_plano_estrategico', 'id': '241286623'},
#                         {'question': 'A\xa0instituição segue um modelo de gestão da qualidade definido para a prestação do serviço? (ex: ISO 9000/9001)', 'column': 'sn_modelo_gestao_qualidade', 'id': '241286624'},
#                         {'question': 'A instituição possui processo regular de avaliação da qualidade do serviço prestado?', 'column': 'sn_avaliacao_qualidade_regular', 'id': '241286626'},
#                         {'question': 'Há pessoas dedicadas exclusivamente à avaliação da qualidade?', 'column': 'sn_pessoas_exclusiv_qualidade', 'id': '241286627'},
#                         {'question': 'Há uma ferramenta para que o usuário possa avaliar sua satisfação quanto ao serviço recebido?', 'column': 'sn_ferramenta_aval_satisfacao', 'id': '241286628'},
#                         {'question': 'Os usuários são envolvidos nos processos de melhoria do serviço?', 'column': 'sn_usuarios_envolv_melhoria', 'id': '241286629'},
#                         {'question': 'Há alianças, parcerias, iniciativas de colaboração com outras instituições públicas que visam a melhoria do serviço prestado?', 'column': 'sn_colaboracao_instituicoes', 'id': '241286631'}
#                      ]
#
#
# columns_multiple = [
#                     {'question': 'Indique os percentuais de utilização de cada canal (anual) em que o usuário busca informações sobre o serviço.', 'column': 'rat_buscainf_presencial_antes', 'id': '241286658'},
#                     {'question': 'Indique os percentuais de utilização de cada canal (anual) em que o usuário busca informações sobre o serviço.', 'column': 'rat_buscainf_digital_antes', 'id': '241286658'},
#                     {'question': 'Indique os percentuais de utilização de cada canal (anual) em que o usuário busca informações sobre o serviço.', 'column': 'rat_buscainf_telefone_antes', 'id': '241286658'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) em que o usuário buscaria informações sobre o serviço.', 'column': 'rat_buscainf_presencial_depois', 'id': '244123593'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) em que o usuário buscaria informações sobre o serviço.', 'column': 'rat_buscainf_digital_depois', 'id': '244123593'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) em que o usuário buscaria informações sobre o serviço.', 'column': 'rat_buscainf_telefone_depois', 'id': '244123593'},
#                     {'question': 'Indique o seu nível de concordância com as afirmações abaixo:', 'column': 'cb_transf_conhecimento', 'id': '241286616'},
#                     {'question': 'Indique o seu nível de concordância com as afirmações abaixo:', 'column': 'cb_politica_capacitacao', 'id': '241286616'},
#                     {'question': 'Indique o seu nível de concordância com as afirmações abaixo:', 'column': 'cb_qtd_colab_adequado', 'id': '241286616'},
#                     {'question': 'Indique o seu nível de concordância com as afirmações abaixo:', 'column': 'cb_treinamento_inicio', 'id': '241286616'},
#                     {'question': 'Indique o seu nível de concordância com as afirmações abaixo:', 'column': 'cb_selecao_colaboradores', 'id': '241286616'},
#                     {'question': 'Quais são os documentos necessários para a solicitação do serviço?', 'column': 'doc_necessarios_1', 'id': '241286642'},
#                     {'question': 'Quais são os documentos necessários para a solicitação do serviço?', 'column': 'doc_necessarios_2', 'id': '241286642'},
#                     {'question': 'Quais são os documentos necessários para a solicitação do serviço?', 'column': 'doc_necessarios_3', 'id': '241286642'},
#                     {'question': 'Quais são os documentos necessários para a solicitação do serviço?', 'column': 'doc_necessarios_4', 'id': '241286642'},
#                     {'question': 'Quais são os documentos necessários para a solicitação do serviço?', 'column': 'doc_necessarios_5', 'id': '241286642'},
#                     {'question': 'Após a transformação do serviço, estime o percentual de redução do número de documentos solicitados ao usuário.', 'column': 'red_docs_solicitados', 'id': '241286656'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'inform_docs_necessarios', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'inform_etapas_necessarias', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'realizar_agendamento', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'consultar_agendamento', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'solicitar_servico', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'acompanhar_servico', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'registrar_reclamacao', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'resposta_reclamacao', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'assinar_documento', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'fazer_pagamento', 'id': '241286619'},
#                     {'question': 'Com relação ao serviço, indique seu nível de concordância com as seguintes afirmações:', 'column': 'disponibilidade_sistemas', 'id': '241286620'},
#                     {'question': 'Com relação ao serviço, indique seu nível de concordância com as seguintes afirmações:', 'column': 'facilita_gestao', 'id': '241286620'},
#                     {'question': 'Com relação ao serviço, indique seu nível de concordância com as seguintes afirmações:', 'column': 'informacoes_confiaveis', 'id': '241286620'},
#                     {'question': 'Com relação ao serviço, indique seu nível de concordância com as seguintes afirmações:', 'column': 'suporte_completo_servico', 'id': '241286620'},
#                     {'question': 'Com relação ao serviço, indique seu nível de concordância com as seguintes afirmações:', 'column': 'dados_formato_aberto', 'id': '241286620'},
#                     {'question': 'Com relação ao serviço, indique seu nível de concordância com as seguintes afirmações:', 'column': 'acessibilidade_sistema', 'id': '241286620'},
#                     {'question': 'Indique o seu nível de concordância com as seguintes afirmações:', 'column': 'reduzir_qtd_documentos', 'id': '241286621'},
#                     {'question': 'Indique o seu nível de concordância com as seguintes afirmações:', 'column': 'divulgacao_desempenho', 'id': '241286621'},
#                     {'question': 'Indique o seu nível de\xa0concordância com as seguintes afirmações:', 'column': 'ad_missao_servicos', 'id': '241286625'},
#                     {'question': 'Indique o seu nível de\xa0concordância com as seguintes afirmações:', 'column': 'ad_monitora_qualidade', 'id': '241286625'},
#                     {'question': 'Indique o seu nível de\xa0concordância com as seguintes afirmações:', 'column': 'ad_divulga_servicos', 'id': '241286625'},
#                     {'question': 'Indique o seu nível de\xa0concordância com as seguintes afirmações:', 'column': 'ad_melhoria_processos', 'id': '241286625'},
#                     {'question': 'Indique seu nível de concordância com a seguinte afirmação:', 'column': 'estrategia_divulgacao_efetiva', 'id': '241286630'},
#                     {'question': 'Indique o seu nível de concordância com a seguinte afirmação:', 'column': 'proatividade_divulgacao_informacoes', 'id': '241286632'}]
#
# columns_other = [
#                     {'question': 'nome_servico_outro', 'column': 'nome_servico_outro', 'id': '1646383625'},
#                     {'question': 'canais_oferecidos_outro', 'column': 'canais_oferecidos_outro', 'id': '1646383431'},
#                     {'question': 'rat_utilizacao_antes_outro', 'column': 'rat_utilizacao_antes_outro', 'id': '1646383472'},
#                     {'question': 'rat_utilizacao_depois_outro', 'column': 'rat_utilizacao_depois_outro', 'id': '1646383625'},
#                     {'question': 'representante_pj_outro', 'column': 'representante_pj_outro', 'id': '1646382999'},
#                     {'question': 'doc_necessarios_outro', 'column': 'doc_necessarios_outro', 'id': '1646382985'},
#                     {'question': 'alteracoes_custos_usuario_outro', 'column': 'alteracoes_custos_usuario_outro', 'id': '1646383005'},
#                     {'question': 'acoes_internet_outro', 'column': 'acoes_internet_outro', 'id': '1646383290'},
#                     {'question': 'adequabilidade_sistemas', 'column': 'adequabilidade_sistemas', 'id': '1646383340'},
#                     {'question': 'melhorias_servico_outro', 'column': 'melhorias_servico_outro', 'id': '1646383282'},
#                     {'question': 'colaboracao_instituicoes_outro', 'column': 'colaboracao_instituicoes_outro', 'id': '1646382988'}]
#
# columns_matrix = [
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_antes_presencial', 'id': '241286649'},
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_antes_digital', 'id': '241286649'},
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_antes_telefone', 'id': '241286649'},
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_antes_postal', 'id': '241286649'},
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_antes_presencial', 'id': '241286649'},
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_antes_digital', 'id': '241286649'},
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_antes_telefone', 'id': '241286649'},
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_antes_postal', 'id': '241286649'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_depois_presencial', 'id': '241286657'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_depois_digital', 'id': '241286657'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_depois_telefone', 'id': '241286657'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_depois_postal', 'id': '241286657'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_depois_presencial', 'id': '241286657'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_depois_digital', 'id': '241286657'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_depois_telefone', 'id': '241286657'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_depois_postal', 'id': '241286657'},
#                     {'question': 'Antes da transformação do serviço, indique quantos colaboradores se dedicam a ofertar o serviço e qual é o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'qtd_servidores_antes', 'id': '241286646'},
#                     {'question': 'Antes da transformação do serviço, indique quantos colaboradores se dedicam a ofertar o serviço e qual é o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'percentual_servidores_antes', 'id': '241286646'},
#                     {'question': 'Antes da transformação do serviço, indique quantos colaboradores se dedicam a ofertar o serviço e qual é o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'qtd_terceirizados_antes', 'id': '241286646'},
#                     {'question': 'Antes da transformação do serviço, indique quantos colaboradores se dedicam a ofertar o serviço e qual é o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'percentual_terceirizados_antes', 'id': '241286646'},
#                     {'question': 'Após a transformação do serviço, estime quantos colaboradores se dedicariam a ofertar o serviço e qual seria o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'qtd_servidores_depois', 'id': '244127646'},
#                     {'question': 'Após a transformação do serviço, estime quantos colaboradores se dedicariam a ofertar o serviço e qual seria o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'percentual_servidores_depois', 'id': '244127646'},
#                     {'question': 'Após a transformação do serviço, estime quantos colaboradores se dedicariam a ofertar o serviço e qual seria o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'qtd_terceirizados_depois', 'id': '244127646'},
#                     {'question': 'Após a transformação do serviço, estime quantos colaboradores se dedicariam a ofertar o serviço e qual seria o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'percentual_terceirizados_depois', 'id': '244127646'}
#                 ]

