
columns_simple = [{"id": '241294964', 'column': 'qtd_servicos'},
                  {"id": '241286639', 'column': 'respondente_nome'},
                  {"id": '241286654', 'column': 'respondente_email'},{"id": '241286655', 'column': 'respondente_telefone'},
                  {"id": '241286637', 'column': 'normas'},
                  {"id": '241286641', 'column': 'volume_anual'},
                  {"id": '241286613', 'column': 'qtd_areas_envolvidas'},
                  {"id": '241286635', 'column': 'qtd_dias_espera'},
                  {"id": '241286636', 'column': 'qtd_interacoes'},
                  {"id": '241286647', 'column': 'qtd_pessoas_implantacao'},
                  {"id": '241286648', 'column': 'tempo_pessoas_implantacao'}]

columns_categoric = [
                    {"id": '241301514', 'column': 'organizacao'},{"id": '241286634', 'column': 'nome_servico'},{"id": '241286638', 'column': 'tipo_usuario'},
                    {"id": '241286650', 'column': 'forma_prestacao'},{"id": '241286610', 'column': 'sn_medicao_tempo_entrega'},
                    {"id": '241286611', 'column': 'canais_oferecidos'},{"id": '241286640', 'column': 'sn_processo_aval_qualidade'},
                    {"id": '241286612', 'column': 'sn_usa_reclamacoes'},{"id": '241286614', 'column': 'sn_capacitacao_colaboradores'},
                    {"id": '241286615', 'column': 'sn_incentivo_colaboradores'},
                    {"id": '241286617', 'column': 'custo_instituicao'},
                    {"id": '241286618', 'column': 'sn_custo_rh_total'},
                    {"id": '241286622', 'column': 'sn_custo_usuario_total'},
                    {"id": '241286633', 'column': 'custo_usuario'},
                    {"id": '241286643', 'column': 'renda_mensal_usuario'},
                    {"id": '241286644', 'column': 'representante_pj'},
                    {"id": '241286652', 'column': 'sn_cadastro_solicitacoes'},
                    {"id": '241286623', 'column': 'sn_servico_plano_estrategico'},
                    {"id": '241286624', 'column': 'sn_modelo_gestao_qualidade'},
                    {"id": '241286626', 'column': 'sn_avaliacao_qualidade_regular'},
                    {"id": '241286627', 'column': 'sn_pessoas_exclusiv_qualidade'},
                    {"id": '241286628', 'column': 'sn_ferramenta_aval_satisfacao'},
                    {"id": '241286629', 'column': 'sn_usuarios_envolv_melhoria'},
                    {"id": '241286631', 'column': 'sn_colaboracao_instituicoes'}]

columns_multiple = [
            {"id": '241286658', 'sub_id': '1646383684', 'column': 'rat_buscainf_presencial_antes'},
            {"id": '241286658', 'sub_id': '1646383685', 'column': 'rat_buscainf_digital_antes'},
            {"id": '241286658', 'sub_id': '1646383687', 'column': 'rat_buscainf_telefone_antes'},

            {"id": '244123593', 'sub_id': '1664161497', 'column': 'rat_buscainf_presencial_depois'},
            {"id": '244123593', 'sub_id': '1664161498', 'column': 'rat_buscainf_digital_depois'},
            {"id": '244123593', 'sub_id': '1664161499', 'column': 'rat_buscainf_telefone_depois'},

            {"id": '241286616', 'sub_id': '1646382796', 'column': 'cb_transf_conhecimento'},
            {"id": '241286616', 'sub_id': '1646382797', 'column': 'cb_politica_capacitacao'},
            {"id": '241286616', 'sub_id': '1646382798', 'column': 'cb_qtd_colab_adequado'},
            {"id": '241286616', 'sub_id': '1646382799', 'column': 'cb_treinamento_inicio'},
            {"id": '241286616', 'sub_id': '1646382800', 'column': 'cb_selecao_colaboradores'},
            {"id": '241286642', 'sub_id': '1646382982', 'column': 'doc_necessarios_1'},
            {"id": '241286642', 'sub_id': '1646383008', 'column': 'doc_necessarios_2'},
            {"id": '241286642', 'sub_id': '1646383010', 'column': 'doc_necessarios_3'},
            {"id": '241286642', 'sub_id': '1646383011', 'column': 'doc_necessarios_4'},
            {"id": '241286642', 'sub_id': '1646383012', 'column': 'doc_necessarios_5'},
            {"id": '241286656', 'sub_id': '1646383518', 'column': 'red_docs_solicitados'},
            {"id": '241286619', 'sub_id': '1646382807', 'column': 'inform_docs_necessarios'},
            {"id": '241286619', 'sub_id': '1646382924', 'column': 'inform_etapas_necessarias'},
            {"id": '241286619', 'sub_id': '1646382808', 'column': 'realizar_agendamento'},
            {"id": '241286619', 'sub_id': '1646382809', 'column': 'consultar_agendamento'},
            {"id": '241286619', 'sub_id': '1646382810', 'column': 'solicitar_servico'},
            {"id": '241286619', 'sub_id': '1646382811', 'column': 'acompanhar_servico'},
            {"id": '241286619', 'sub_id': '1646382925', 'column': 'registrar_reclamacao'},
            {"id": '241286619', 'sub_id': '1646382812', 'column': 'resposta_reclamacao'},
            {"id": '241286619', 'sub_id': '1646382926', 'column': 'assinar_documento'},
            {"id": '241286619', 'sub_id': '1646382927', 'column': 'fazer_pagamento'},
            {"id": '241286620', 'sub_id': '1646382813', 'column': 'disponibilidade_sistemas'},
            {"id": '241286620', 'sub_id': '1646382814', 'column': 'facilita_gestao'},
            {"id": '241286620', 'sub_id': '1646382815', 'column': 'informacoes_confiaveis'},
            {"id": '241286620', 'sub_id': '1646382816', 'column': 'suporte_completo_servico'},
            {"id": '241286620', 'sub_id': '1646382950', 'column': 'dados_formato_aberto'},
            {"id": '241286620', 'sub_id': '1646382951', 'column': 'acessibilidade_sistema'},
            {"id": '241286621', 'sub_id': '1646382821', 'column': 'reduzir_qtd_documentos'},
            {"id": '241286621', 'sub_id': '1646382822', 'column': 'divulgacao_desempenho'},
            {"id": '241286625', 'sub_id': '1646382833', 'column': 'ad_missao_servicos'},
            {"id": '241286625', 'sub_id': '1646382834', 'column': 'ad_monitora_qualidade'},
            {"id": '241286625', 'sub_id': '1646382835', 'column': 'ad_divulga_servicos'},
            {"id": '241286625', 'sub_id': '1646382836', 'column': 'ad_melhoria_processos'},
            {"id": '241286630', 'sub_id': '1646382849', 'column': 'estrategia_divulgacao_efetiva'},
            {"id": '241286632', 'sub_id': '1646382856', 'column': 'proatividade_divulgacao_informacoes'},
            {"id": '000000000000000000000000000000000', 'sub_id': '1646382856', 'column': 'sistema_etapas'},
            ]

columns_matrix = [
    {"id": '241286649', 'row_id': '1646383470', 'col_id': '1646383535', 'column': 'rat_solicitacao_antes_presencial'},
    {"id": '241286649', 'row_id': '1646383471', 'col_id': '1646383535', 'column': 'rat_solicitacao_antes_digital'},
    {"id": '241286649', 'row_id': '1646383531', 'col_id': '1646383535', 'column': 'rat_solicitacao_antes_telefone'},
    {"id": '241286649', 'row_id': '1646383530', 'col_id': '1646383535', 'column': 'rat_solicitacao_antes_postal'},
    {"id": '241286649', 'row_id': '1646383470', 'col_id': '1646383558', 'column': 'rat_entrega_antes_presencial'},
    {"id": '241286649', 'row_id': '1646383471', 'col_id': '1646383558', 'column': 'rat_entrega_antes_digital'},
    {"id": '241286649', 'row_id': '1646383531', 'col_id': '1646383558', 'column': 'rat_entrega_antes_telefone'},
    {"id": '241286649', 'row_id': '1646383530', 'col_id': '1646383558', 'column': 'rat_entrega_antes_postal'},
    {"id": '241286657', 'row_id': '1646383623', 'col_id': '1646383654', 'column': 'rat_entrega_depois_presencial'},
    {"id": '241286657', 'row_id': '1646383624', 'col_id': '1646383654', 'column': 'rat_entrega_depois_digital'},
    {"id": '241286657', 'row_id': '1646383627', 'col_id': '1646383654', 'column': 'rat_entrega_depois_telefone'},
    {"id": '241286657', 'row_id': '1646383626', 'col_id': '1646383654', 'column': 'rat_entrega_depois_postal'},
    {"id": '241286657', 'row_id': '1646383623', 'col_id': '1646383631', 'column': 'rat_solicitacao_depois_presencial'},
    {"id": '241286657', 'row_id': '1646383624', 'col_id': '1646383631', 'column': 'rat_solicitacao_depois_digital'},
    {"id": '241286657', 'row_id': '1646383627', 'col_id': '1646383631', 'column': 'rat_solicitacao_depois_telefone'},
    {"id": '241286657', 'row_id': '1646383626', 'col_id': '1646383631', 'column': 'rat_solicitacao_depois_postal'},
    {'id': '241286646', "row_id": '1646383182', 'col_id': '1646383186', 'column': 'qtd_servidores_antes'},
    {'id': '241286646', "row_id": '1646383182', 'col_id': '1646383283', 'column': 'percentual_servidores_antes'},
    {'id': '241286646', "row_id": '1646383184', 'col_id': '1646383186', 'column': 'qtd_terceirizados_antes'},
    {'id': '241286646', "row_id": '1646383184', 'col_id': '1646383283', 'column': 'percentual_terceirizados_antes'},

    {'id': '244127646', "row_id": '1664189139', 'col_id': '1664189141', 'column': 'qtd_servidores_depois'},
    {'id': '244127646', "row_id": '1664189139', 'col_id': '1664189231', 'column': 'percentual_servidores_depois'},
    {'id': '244127646', "row_id": '1664189140', 'col_id': '1664189141', 'column': 'qtd_terceirizados_depois'},
    {'id': '244127646', "row_id": '1664189140', 'col_id': '1664189231', 'column': 'percentual_terceirizados_depois'},

    ]


columns_other = [
    {"id": '1646383625', 'column': 'nome_servico_outro'},
    {"id": '1646383431', 'column': 'canais_oferecidos_outro'},
    {"id": '1646383472', 'column': 'rat_utilizacao_antes_outro'},
    {"id": '1646383625', 'column': 'rat_utilizacao_depois_outro'},
    {"id": '1646382999', 'column': 'representante_pj_outro'},
    {"id": '1646382985', 'column': 'doc_necessarios_outro'},
    {"id": '1646383290', 'column': 'acoes_internet_outro'},
    {"id": '1646383340', 'column': 'adequabilidade_sistemas'},
    {"id": '1646383282', 'column': 'melhorias_servico_outro'},
    {"id": '1646382988', 'column': 'colaboracao_instituicoes_outro'},
                 ]
#
# columns_simple = [
#                     {'question': 'Quantos serviços você coordena?', 'column': 'qtd_servicos', 'id': '241294964'},
#                     {'question': 'Qual é o seu nome?', 'column': 'respondente_nome', 'id': '241286639'},
#                     {'question': 'Qual é o seu email?(OBS: formato xxxxxx@xxxxxx.gov.br)', 'column': 'respondente_email', 'id': '241286654'},
#                     {'question': 'Qual é o seu telefone?(Obs: todos os números juntos no formato 9999999999, incluindo DDD)', 'column': 'respondente_telefone', 'id': '241286655'},
#                     {'question': 'Quais são as principais normas que regulam o serviço?(ex: leis, decretos, instruções normativas, portarias, etc)', 'column': 'normas', 'id': '241286637'},
#                     {'question': 'Qual é a estimativa do volume anual de solicitações do serviço?(Obs: é possível digitar o número desejado no campo à direita, sem utilizar a barra de rolagem)', 'column': 'volume_anual', 'id': '241286641'},
#                     {'question': 'Quantas áreas da instituição estão envolvidas na prestação do serviço?(área: setor que representa menor nível hierárquico no organograma da instituição)', 'column': 'qtd_areas_envolvidas', 'id': '241286613'},
#                     {'question': 'Quantos dias o usuário espera até a efetiva entrega do serviço?', 'column': 'qtd_dias_espera', 'id': '241286635'},
#                     {'question': 'De forma estimada, quantas vezes o usuário interage com a instituição até a entrega do serviço?(interação: cada vez que um\xa0usuário se relaciona com a\xa0instituição durante a prestação do serviço)', 'column': 'qtd_interacoes', 'id': '241286636'},
#                     {'question': 'Quantos colaboradores se dedicariam ao projeto de desenvolvimento e implantação da política de transformação do serviço?', 'column': 'qtd_pessoas_implantacao', 'id': '241286647'},
#                     {'question': 'Qual seria o tempo estimado de dedicação semanal dos colaboradores em horas?', 'column': 'tempo_pessoas_implantacao', 'id': '241286648'}
#                 ]
#
# columns_categoric = [
#                         {'question': 'A qual instituição você pertence?', 'column': 'organizacao', 'id': '241301514'},
#                         {'question': 'Informe o nome do serviço que será avaliado nessa pesquisa.(OBS: é possível buscar por serviço clicando no menu suspenso e digitando a primeira letra do nome do serviço desejado)', 'column': 'nome_servico', 'id': '241286634'},
#                         {'question': 'O serviço\xa0é oferecido a pessoas físicas, jurídicas ou ambas?', 'column': 'tipo_usuario', 'id': '241286638'},
#                         {'question': 'Qual é a forma de prestação do serviço?', 'column': 'forma_prestacao', 'id': '241286650'},
#                         {'question': 'Há medições do tempo de espera do usuário até a entrega do serviço?(entrega: ato administrativo final que implica no recebimento do serviço pelo usuário)', 'column': 'sn_medicao_tempo_entrega', 'id': '241286610'},
#                         {'question': 'Quais canais de atendimento são oferecidos para o relacionamento com os usuários do serviço?', 'column': 'canais_oferecidos', 'id': '241286611'},
#                         {'question': 'Há processo de avaliação da qualidade do atendimento oferecido ao usuário do serviço?', 'column': 'sn_processo_aval_qualidade', 'id': '241286640'},
#                         {'question': 'A sua instituição faz uso dos dados de reclamações e sugestões para a melhoria do serviço?', 'column': 'sn_usa_reclamacoes', 'id': '241286612'},
#                         {'question': 'Há ações de capacitação da instituição voltadas diretamente para o serviço analisado (considere apenas os treinamentos ligados ao serviço analisado, e não da instituição como um todo)?', 'column': 'sn_capacitacao_colaboradores', 'id': '241286614'},
#                         {'question': 'São oferecidos incentivos aos colaboradores pelo seu desempenho associado à melhoria da qualidade dos serviços?', 'column': 'sn_incentivo_colaboradores', 'id': '241286615'},
#                         {'question': 'Qual é a estimativa de custo anual total do serviço para a instituição? (Itens: recursos humanos/quadro de colaboradores, locação ou manutenção da infraestrutura e Tecnologia da Informação)', 'column': 'custo_instituicao', 'id': '241286617'},
#                         {'question': 'Há indicador do custo dos Recursos Humanos em relação ao gasto total com o serviço?', 'column': 'sn_custo_rh_total', 'id': '241286618'},
#                         {'question': 'Há mensuração do custo total para o usuário? (Custo total para o usuário: inclui taxas, gastos com deslocamento, alimentação, tempo de espera, etc)', 'column': 'sn_custo_usuario_total', 'id': '241286622'},
#                         {'question': 'Caso "Sim", quais são os custos estimados para o usuário (taxas, tarifas, custos de deslocamento, outros)?', 'column': 'custo_usuario', 'id': '241286633'},
#                         {'question': 'De forma estimada, qual seria a renda média mensal do usuário típico do serviço?', 'column': 'renda_mensal_usuario', 'id': '241286643'},
#                         {'question': 'Se o solicitante é pessoa jurídica, qual(ais) o(s) perfil(is) profissional(is) mais se aproxima(m) do(s) possível(eis) usuário(s) típico(s) que realizam as atividades exigidas pelo serviço?', 'column': 'representante_pj', 'id': '241286644'},
#                         {'question': 'As solicitações de serviço recebidas geram algum cadastro eletrônico para a instituição?', 'column': 'sn_cadastro_solicitacoes', 'id': '241286652'},
#                         {'question': 'O serviço está contemplado\xa0no plano estratégico da instituição?', 'column': 'sn_servico_plano_estrategico', 'id': '241286623'},
#                         {'question': 'A\xa0instituição segue um modelo de gestão da qualidade definido para a prestação do serviço? (ex: ISO 9000/9001)', 'column': 'sn_modelo_gestao_qualidade', 'id': '241286624'},
#                         {'question': 'A instituição possui processo regular de avaliação da qualidade do serviço prestado?', 'column': 'sn_avaliacao_qualidade_regular', 'id': '241286626'},
#                         {'question': 'Há pessoas dedicadas exclusivamente à avaliação da qualidade?', 'column': 'sn_pessoas_exclusiv_qualidade', 'id': '241286627'},
#                         {'question': 'Há uma ferramenta para que o usuário possa avaliar sua satisfação quanto ao serviço recebido?', 'column': 'sn_ferramenta_aval_satisfacao', 'id': '241286628'},
#                         {'question': 'Os usuários são envolvidos nos processos de melhoria do serviço?', 'column': 'sn_usuarios_envolv_melhoria', 'id': '241286629'},
#                         {'question': 'Há alianças, parcerias, iniciativas de colaboração com outras instituições públicas que visam a melhoria do serviço prestado?', 'column': 'sn_colaboracao_instituicoes', 'id': '241286631'}
#                      ]
#
#
# columns_multiple = [
#                     {'question': 'Indique os percentuais de utilização de cada canal (anual) em que o usuário busca informações sobre o serviço.', 'column': 'rat_buscainf_presencial_antes', 'id': '241286658'},
#                     {'question': 'Indique os percentuais de utilização de cada canal (anual) em que o usuário busca informações sobre o serviço.', 'column': 'rat_buscainf_digital_antes', 'id': '241286658'},
#                     {'question': 'Indique os percentuais de utilização de cada canal (anual) em que o usuário busca informações sobre o serviço.', 'column': 'rat_buscainf_telefone_antes', 'id': '241286658'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) em que o usuário buscaria informações sobre o serviço.', 'column': 'rat_buscainf_presencial_depois', 'id': '244123593'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) em que o usuário buscaria informações sobre o serviço.', 'column': 'rat_buscainf_digital_depois', 'id': '244123593'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) em que o usuário buscaria informações sobre o serviço.', 'column': 'rat_buscainf_telefone_depois', 'id': '244123593'},
#                     {'question': 'Indique o seu nível de concordância com as afirmações abaixo:', 'column': 'cb_transf_conhecimento', 'id': '241286616'},
#                     {'question': 'Indique o seu nível de concordância com as afirmações abaixo:', 'column': 'cb_politica_capacitacao', 'id': '241286616'},
#                     {'question': 'Indique o seu nível de concordância com as afirmações abaixo:', 'column': 'cb_qtd_colab_adequado', 'id': '241286616'},
#                     {'question': 'Indique o seu nível de concordância com as afirmações abaixo:', 'column': 'cb_treinamento_inicio', 'id': '241286616'},
#                     {'question': 'Indique o seu nível de concordância com as afirmações abaixo:', 'column': 'cb_selecao_colaboradores', 'id': '241286616'},
#                     {'question': 'Quais são os documentos necessários para a solicitação do serviço?', 'column': 'doc_necessarios_1', 'id': '241286642'},
#                     {'question': 'Quais são os documentos necessários para a solicitação do serviço?', 'column': 'doc_necessarios_2', 'id': '241286642'},
#                     {'question': 'Quais são os documentos necessários para a solicitação do serviço?', 'column': 'doc_necessarios_3', 'id': '241286642'},
#                     {'question': 'Quais são os documentos necessários para a solicitação do serviço?', 'column': 'doc_necessarios_4', 'id': '241286642'},
#                     {'question': 'Quais são os documentos necessários para a solicitação do serviço?', 'column': 'doc_necessarios_5', 'id': '241286642'},
#                     {'question': 'Após a transformação do serviço, estime o percentual de redução do número de documentos solicitados ao usuário.', 'column': 'red_docs_solicitados', 'id': '241286656'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'inform_docs_necessarios', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'inform_etapas_necessarias', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'realizar_agendamento', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'consultar_agendamento', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'solicitar_servico', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'acompanhar_servico', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'registrar_reclamacao', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'resposta_reclamacao', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'assinar_documento', 'id': '241286619'},
#                     {'question': 'Indique as ações que hoje podem ser realizadas pelo\xa0usuário via internet:', 'column': 'fazer_pagamento', 'id': '241286619'},
#                     {'question': 'Com relação ao serviço, indique seu nível de concordância com as seguintes afirmações:', 'column': 'disponibilidade_sistemas', 'id': '241286620'},
#                     {'question': 'Com relação ao serviço, indique seu nível de concordância com as seguintes afirmações:', 'column': 'facilita_gestao', 'id': '241286620'},
#                     {'question': 'Com relação ao serviço, indique seu nível de concordância com as seguintes afirmações:', 'column': 'informacoes_confiaveis', 'id': '241286620'},
#                     {'question': 'Com relação ao serviço, indique seu nível de concordância com as seguintes afirmações:', 'column': 'suporte_completo_servico', 'id': '241286620'},
#                     {'question': 'Com relação ao serviço, indique seu nível de concordância com as seguintes afirmações:', 'column': 'dados_formato_aberto', 'id': '241286620'},
#                     {'question': 'Com relação ao serviço, indique seu nível de concordância com as seguintes afirmações:', 'column': 'acessibilidade_sistema', 'id': '241286620'},
#                     {'question': 'Indique o seu nível de concordância com as seguintes afirmações:', 'column': 'reduzir_qtd_documentos', 'id': '241286621'},
#                     {'question': 'Indique o seu nível de concordância com as seguintes afirmações:', 'column': 'divulgacao_desempenho', 'id': '241286621'},
#                     {'question': 'Indique o seu nível de\xa0concordância com as seguintes afirmações:', 'column': 'ad_missao_servicos', 'id': '241286625'},
#                     {'question': 'Indique o seu nível de\xa0concordância com as seguintes afirmações:', 'column': 'ad_monitora_qualidade', 'id': '241286625'},
#                     {'question': 'Indique o seu nível de\xa0concordância com as seguintes afirmações:', 'column': 'ad_divulga_servicos', 'id': '241286625'},
#                     {'question': 'Indique o seu nível de\xa0concordância com as seguintes afirmações:', 'column': 'ad_melhoria_processos', 'id': '241286625'},
#                     {'question': 'Indique seu nível de concordância com a seguinte afirmação:', 'column': 'estrategia_divulgacao_efetiva', 'id': '241286630'},
#                     {'question': 'Indique o seu nível de concordância com a seguinte afirmação:', 'column': 'proatividade_divulgacao_informacoes', 'id': '241286632'}]
#
# columns_other = [
#                     {'question': 'nome_servico_outro', 'column': 'nome_servico_outro', 'id': '1646383625'},
#                     {'question': 'canais_oferecidos_outro', 'column': 'canais_oferecidos_outro', 'id': '1646383431'},
#                     {'question': 'rat_utilizacao_antes_outro', 'column': 'rat_utilizacao_antes_outro', 'id': '1646383472'},
#                     {'question': 'rat_utilizacao_depois_outro', 'column': 'rat_utilizacao_depois_outro', 'id': '1646383625'},
#                     {'question': 'representante_pj_outro', 'column': 'representante_pj_outro', 'id': '1646382999'},
#                     {'question': 'doc_necessarios_outro', 'column': 'doc_necessarios_outro', 'id': '1646382985'},
#                     {'question': 'alteracoes_custos_usuario_outro', 'column': 'alteracoes_custos_usuario_outro', 'id': '1646383005'},
#                     {'question': 'acoes_internet_outro', 'column': 'acoes_internet_outro', 'id': '1646383290'},
#                     {'question': 'adequabilidade_sistemas', 'column': 'adequabilidade_sistemas', 'id': '1646383340'},
#                     {'question': 'melhorias_servico_outro', 'column': 'melhorias_servico_outro', 'id': '1646383282'},
#                     {'question': 'colaboracao_instituicoes_outro', 'column': 'colaboracao_instituicoes_outro', 'id': '1646382988'}]
#
# columns_matrix = [
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_antes_presencial', 'id': '241286649'},
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_antes_digital', 'id': '241286649'},
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_antes_telefone', 'id': '241286649'},
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_antes_postal', 'id': '241286649'},
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_antes_presencial', 'id': '241286649'},
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_antes_digital', 'id': '241286649'},
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_antes_telefone', 'id': '241286649'},
#                     {'question': 'Antes da transformação do serviço, indique os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_antes_postal', 'id': '241286649'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_depois_presencial', 'id': '241286657'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_depois_digital', 'id': '241286657'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_depois_telefone', 'id': '241286657'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_entrega_depois_postal', 'id': '241286657'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_depois_presencial', 'id': '241286657'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_depois_digital', 'id': '241286657'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_depois_telefone', 'id': '241286657'},
#                     {'question': 'Após a transformação do serviço, estime os percentuais de utilização de cada canal (anual) para a solicitação e entrega do serviço.', 'column': 'rat_solicitacao_depois_postal', 'id': '241286657'},
#                     {'question': 'Antes da transformação do serviço, indique quantos colaboradores se dedicam a ofertar o serviço e qual é o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'qtd_servidores_antes', 'id': '241286646'},
#                     {'question': 'Antes da transformação do serviço, indique quantos colaboradores se dedicam a ofertar o serviço e qual é o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'percentual_servidores_antes', 'id': '241286646'},
#                     {'question': 'Antes da transformação do serviço, indique quantos colaboradores se dedicam a ofertar o serviço e qual é o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'qtd_terceirizados_antes', 'id': '241286646'},
#                     {'question': 'Antes da transformação do serviço, indique quantos colaboradores se dedicam a ofertar o serviço e qual é o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'percentual_terceirizados_antes', 'id': '241286646'},
#                     {'question': 'Após a transformação do serviço, estime quantos colaboradores se dedicariam a ofertar o serviço e qual seria o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'qtd_servidores_depois', 'id': '244127646'},
#                     {'question': 'Após a transformação do serviço, estime quantos colaboradores se dedicariam a ofertar o serviço e qual seria o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'percentual_servidores_depois', 'id': '244127646'},
#                     {'question': 'Após a transformação do serviço, estime quantos colaboradores se dedicariam a ofertar o serviço e qual seria o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'qtd_terceirizados_depois', 'id': '244127646'},
#                     {'question': 'Após a transformação do serviço, estime quantos colaboradores se dedicariam a ofertar o serviço e qual seria o percentual médio de tempo dos colaboradores dedicados à oferta do serviço.', 'column': 'percentual_terceirizados_depois', 'id': '244127646'}
#                 ]

